#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("IgoNudger.Droid.Resource", IsApplication=true)]

namespace IgoNudger.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int Check1 = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int Text1 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int Text2 = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int addTaskButton = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int completedSwitch = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int descriptionEdit = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int nameEdit = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int saveButton = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int settingsButton = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int taskList = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TaskDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TaskListItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int addTask = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int completedText = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int pref_notification_send = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int pref_notification_title = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int report_ntf_label = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int saveButton = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int settings_name = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int taskDetailsTitle = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
